server:
  port: 8888
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/money
    username: postgres
    password: "0440"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
security:
  oauth2:
    client:
      clientId: 137495676642-kh3d21svt0q9dqv27mbg3n2s7ru9ggqp.apps.googleusercontent.com
      clientSecret: qynBBYSElnpmg2df-1lGQSrV
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true